name: osprey_app
description: "A new Flutter project."

publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # File Picker for uploading documents
  file_picker: ^8.0.7

  # UI & Material Components
  cupertino_icons: ^1.0.8

  # 🔥 Updated Firebase Dependencies
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.6.0

  # State Management
  provider: ^6.1.2

  # Navigation & Routing
  go_router: ^13.2.0

  # UI Enhancements
  flutter_animate: ^4.5.0  # For animations
  cached_network_image: ^3.3.1  # Optimized image loading
  google_sign_in: ^6.3.0
  google_nav_bar: ^5.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Assets Section
  assets:
    - assets/google.png  
    - assets/logo.png
